apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/prometheus-alertmanager"

