apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    app.kubernetes.io/instance: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "secret-uat"
        vault.hashicorp.com/agent-inject-secret-secrets: "secret-uat/data/secrets"
        vault.hashicorp.com/agent-inject-template-secrets: |
          {{- with secret "secret-uat/data/secrets" -}}
          {{- range $k, $v := .Data.data }}
          {{ $k }}="{{ $v }}"
          {{- end }}
          {{- end }}
    spec:
      serviceAccountName: secret-reader
      containers:
      - image: nginx
        name: nginx
        command:
          - "/bin/bash"
          - "-c"
          - "source /vault/secrets/secrets && nginx -g 'daemon off;'"
        resources: {}