apiVersion: v1
kind: PersistentVolume
metadata:
  name: openbao-pv
spec:
  capacity:
    storage: 10Gi  
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/openbao  # Change this to the desired host path
